#!/usr/bin/env node
/* Everlight Digital — SEO head injector.
 *
 * Adds canonical, Open Graph / Twitter card tags, JSON-LD structured data,
 * and the analytics loader to every page. Idempotent: the injected block is
 * fenced by markers, so re-running replaces rather than duplicates.
 *
 *   node tools/seo-inject.mjs          # write
 *   node tools/seo-inject.mjs --check  # report drift, exit 1 if any (CI-safe)
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { globSync } from 'node:fs';
import path from 'node:path';

const ORIGIN = 'https://everlight-digital.com';
const OG_IMAGE = `${ORIGIN}/assets/og/default.png`;
const SITE_NAME = 'Everlight Digital';

/* Google Search Console site-verification token — the `content` value from
   the meta tag GSC hands you under Settings > Ownership verification >
   HTML tag. Renders on the homepage only.

   This is a SECOND method: the property is also verified through a Domain
   property via a DNS TXT record. That's deliberate. A registrar or zone
   migration that drops the TXT record would silently unverify the property
   and stop Search Console collecting data, with no visible error. Two
   independent methods means one migration can't take it down.

   Do not remove this once verified — Google re-checks it periodically. */
const GSC_VERIFICATION = 'Rpx8ex6yfLd6L0MU3ovfJ6DNDxRMbKY2iKTqqBHPg0U';
const START = '<!-- seo:start (generated by tools/seo-inject.mjs — do not hand-edit) -->';
const END = '<!-- seo:end -->';
const CHECK = process.argv.includes('--check');

const ROOT = path.resolve(import.meta.dirname, '..');
const ANCHOR = '<link rel="stylesheet" href="/brand/site.css">';

/** Pages that exist only as includes, not as routes. */
const NOT_A_PAGE = new Set(['brand/partials/footer.html']);

const files = globSync('**/*.html', { cwd: ROOT })
  .filter((f) => !f.startsWith('.git/') && !f.startsWith('tools/'))
  .filter((f) => !NOT_A_PAGE.has(f))
  .sort();

const esc = (s) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/** "journal/foo.html" -> "/journal/foo.html"; index files -> directory URL. */
function urlFor(file) {
  if (file === 'index.html') return `${ORIGIN}/`;
  if (file.endsWith('/index.html')) return `${ORIGIN}/${file.slice(0, -'index.html'.length)}`;
  return `${ORIGIN}/${file}`;
}

function pick(html, re) {
  const m = html.match(re);
  return m ? m[1] : null;
}

const FALLBACK_DATE = '2026-07-12';

/** Date the commit that FIRST added this file landed.
 *  Must not be the last-commit date: editing an article — or regenerating
 *  this very block — would otherwise reset its publish date, which both
 *  misleads readers and churns the --check gate on every commit. */
function datePublished(file) {
  try {
    const out = execSync(
      `git log --diff-filter=A --format=%cs -- ${JSON.stringify(file)}`,
      { cwd: ROOT, encoding: 'utf8' }
    ).trim();
    // Oldest add is last; a file re-added after a rename yields several.
    const first = out.split('\n').filter(Boolean).pop();
    return first || FALLBACK_DATE;
  } catch {
    return FALLBACK_DATE;
  }
}

/** Date of the file's most recent commit. Converges: regenerating and
 *  committing on the same day reproduces the same value. */
function dateModified(file) {
  try {
    const out = execSync(`git log -1 --format=%cs -- ${JSON.stringify(file)}`, {
      cwd: ROOT,
      encoding: 'utf8',
    }).trim();
    return out || FALLBACK_DATE;
  } catch {
    return FALLBACK_DATE;
  }
}

function classify(file) {
  if (file === 'index.html') return 'home';
  if (file.startsWith('apps/')) return 'app';
  if (file === 'journal/index.html') return 'journal-index';
  if (file.startsWith('journal/')) return 'article';
  return 'utility';
}

/** App story pages -> the thing they're selling. */
const APPS = {
  'apps/pilgrim.html': {
    name: 'Pilgrim',
    os: 'iOS',
    category: 'LifestyleApplication',
    url: 'https://apps.apple.com/us/app/pilgrim-bible-prayer/id6769929244',
  },
  'apps/regen.html': {
    name: 'Regen',
    os: 'iOS',
    category: 'HealthApplication',
    url: 'https://apps.apple.com/us/app/id6764216927',
  },
  'apps/shepherd.html': {
    name: 'Shepherd',
    os: 'Web',
    category: 'BusinessApplication',
    url: 'https://www.pastorshepherd.com',
  },
  'apps/olive.html': {
    name: 'Olive',
    os: 'iOS',
    category: 'LifestyleApplication',
    url: `${ORIGIN}/apps/olive.html`,
  },
};

function jsonLd(file, kind, title, desc) {
  const url = urlFor(file);
  const org = {
    '@type': 'Organization',
    '@id': `${ORIGIN}/#org`,
    name: SITE_NAME,
    url: `${ORIGIN}/`,
    logo: `${ORIGIN}/brand/lockup-light.svg`,
    email: 'brendan@everlight-digital.com',
    description: 'A one-person studio building calm, honest software for faith, family, and the everyday.',
  };

  if (kind === 'home') {
    return [
      org,
      {
        '@type': 'WebSite',
        '@id': `${ORIGIN}/#website`,
        name: SITE_NAME,
        url: `${ORIGIN}/`,
        publisher: { '@id': `${ORIGIN}/#org` },
      },
    ];
  }

  if (kind === 'app') {
    const app = APPS[file];
    if (!app) return null;
    return [
      {
        '@type': 'SoftwareApplication',
        name: app.name,
        description: desc,
        url: app.url,
        operatingSystem: app.os,
        applicationCategory: app.category,
        publisher: { '@id': `${ORIGIN}/#org` },
      },
    ];
  }

  if (kind === 'article') {
    return [
      {
        '@type': 'Article',
        headline: title,
        description: desc,
        url,
        image: OG_IMAGE,
        datePublished: datePublished(file),
        dateModified: dateModified(file),
        author: { '@type': 'Person', name: 'Brendan Pratt' },
        publisher: { '@id': `${ORIGIN}/#org` },
        mainEntityOfPage: { '@type': 'WebPage', '@id': url },
      },
    ];
  }

  return null;
}

function buildBlock(file, html) {
  const kind = classify(file);
  const url = urlFor(file);

  const rawTitle = pick(html, /<title>([\s\S]*?)<\/title>/) ?? SITE_NAME;
  // Strip the shared " — Everlight Digital" suffix for OG/headline use.
  const title = rawTitle.replace(/\s+—\s+Everlight Digital\s*$/, '').trim();
  const desc =
    pick(html, /<meta name="description" content="([^"]*)"/) ??
    'Calm, honest software for faith, family, and the everyday.';

  const ogType = kind === 'article' ? 'article' : 'website';
  const lines = [START, `<link rel="canonical" href="${url}">`];

  if (kind === 'home' && GSC_VERIFICATION) {
    lines.push(`<meta name="google-site-verification" content="${esc(GSC_VERIFICATION)}">`);
  }

  // Pages that already hand-authored og:title/og:description keep theirs;
  // we only add what's missing so editorial copy is never clobbered.
  if (!/og:title/.test(html)) lines.push(`<meta property="og:title" content="${esc(title)}">`);
  if (!/og:description/.test(html)) lines.push(`<meta property="og:description" content="${esc(desc)}">`);
  if (!/og:type/.test(html)) lines.push(`<meta property="og:type" content="${ogType}">`);
  if (!/og:url/.test(html)) lines.push(`<meta property="og:url" content="${url}">`);

  lines.push(
    `<meta property="og:site_name" content="${SITE_NAME}">`,
    `<meta property="og:image" content="${OG_IMAGE}">`,
    `<meta property="og:image:width" content="1200">`,
    `<meta property="og:image:height" content="630">`,
    `<meta property="og:image:alt" content="Everlight Digital — calm, honest software.">`,
    `<meta name="twitter:card" content="summary_large_image">`,
    `<meta name="twitter:title" content="${esc(title)}">`,
    `<meta name="twitter:description" content="${esc(desc)}">`,
    `<meta name="twitter:image" content="${OG_IMAGE}">`
  );

  const ld = jsonLd(file, kind, title, desc);
  if (ld) {
    const graph = { '@context': 'https://schema.org', '@graph': ld };
    lines.push(`<script type="application/ld+json">${JSON.stringify(graph)}</script>`);
  }

  lines.push(`<script src="/brand/analytics.js" defer></script>`, END);
  return lines.join('\n');
}

let changed = 0;
const drift = [];

for (const file of files) {
  const abs = path.join(ROOT, file);
  let html = readFileSync(abs, 'utf8');

  if (!html.includes(ANCHOR)) {
    console.error(`SKIP (no site.css anchor): ${file}`);
    continue;
  }

  // Drop any previous block so the rebuild is authoritative.
  const fenced = new RegExp(`${START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${END}\\n?`, 'g');
  const base = html.replace(fenced, '');

  const block = buildBlock(file, base);
  const next = base.replace(ANCHOR, `${block}\n${ANCHOR}`);

  if (next !== html) {
    drift.push(file);
    if (!CHECK) writeFileSync(abs, next);
    changed++;
  }
}

if (CHECK) {
  if (drift.length) {
    console.error(`SEO drift in ${drift.length} file(s):\n  ${drift.join('\n  ')}`);
    process.exit(1);
  }
  console.log(`SEO head up to date across ${files.length} pages.`);
} else {
  console.log(`Injected SEO head into ${changed} of ${files.length} pages.`);
}
